### ISSUE TITLE
openpay/sdk

### ISSUE THREAD

**Issue by PonchoDlr** [open-pay/openpay-magento2-banks#17]
Que tal, cuando intento instalar el módulo de pagos vía SPEI obtengo el siguiente error, actualmente tengo instalado el módulo de pagos con tarjeta en mi e-commerce magento v 2.3.3
![image](https://user-images.githubusercontent.com/73364097/97047808-2272bd80-153f-11eb-8c84-92dc1b705cbd.png)

![image](https://user-images.githubusercontent.com/73364097/97047565-ce67d900-153e-11eb-9417-66ddeda58858.png)

**Comment by jose-openpay** [comment]
Buen día @PonchoDlr 

Para instalar la nueva versión del plugin banks para Magento 2, es necesario que primero actualice su versión del plugin de pago con tarjetas junto con el SDK de PHP. Para ello deberá realizar una actualización múltiple, es decir, actualizar el plugin y el SDK de PHP, le comparto una serie de comandos que te pueden ayudar a hacer está actualización. 

composer clear-cache
composer update openpay/sdk openpay/magento2-cards
bin/magento setup:upgrade
php bin/magento cache:clean

Una vez que se asegure que tiene la última versión de nuestro plugin de tarjetas y del SDK de PHP, no debe tener ningún problema para instalar la última versión del plugin para pagos vía SPEI. 

Saludos !

**Comment by PonchoDlr** [comment]
> Buen día @PonchoDlr
> 
> Para instalar la nueva versión del plugin banks para Magento 2, es necesario que primero actualice su versión del plugin de pago con tarjetas junto con el SDK de PHP. Para ello deberá realizar una actualización múltiple, es decir, actualizar el plugin y el SDK de PHP, le comparto una serie de comandos que te pueden ayudar a hacer está actualización.
> 
> composer clear-cache
> composer update openpay/sdk openpay/magento2-cards
> bin/magento setup:upgrade
> php bin/magento cache:clean
> 
> Una vez que se asegure que tiene la última versión de nuestro plugin de tarjetas y del SDK de PHP, no debe tener ningún problema para instalar la última versión del plugin para pagos vía SPEI.
> 
> Saludos !

de acuerdo, lo intento enseguida.

**Comment by PonchoDlr** [comment]
Problema solucionado, gracias
