### ISSUE TITLE
Webhook devuelve 302 en vez de 200

### ISSUE THREAD

**Issue by vicman10000** [open-pay/openpay-magento2-banks#4]
Al instalar el plugin de Banks para Magento 2.3.0 el webhook devuelve 302

Este error no ocurre si se instala únicamente el plugin para Stores.

Podría ser provocado por estas diferencias:

https://www.diffchecker.com/8srUye83

?

Saludos

**Comment by fedebalderas** [comment]
@vicman10000 Si, faltaba la implementación de la interfaz "CsrfAwareActionInterface". Ya se subió el cambio.

Saludos!

**Comment by vicman10000** [comment]
@fedebalderas gracias por el cambio.

Me sigue regresando 302 alguna idea de por que podría ser?

Muchas gracias!

**Comment by fedebalderas** [comment]
@vicman10000 Estaba revisando que podría ser y parece que Packagist no actualizó la última versión que se publica para Composer (lo tuve que actualizar manualmente), si pudieras probar nuevamente. La versión de nuestro plugin que debería de instalarse debe de ser la 2.3.3.

Saludos!

**Comment by vicman10000** [comment]
@fedebalderas muchas gracias ya quedo resuelto.
